In [1]:
import pathlib
import re

In [2]:
import mywidgets.Tools.uiStyle.MarkupRe as MarkupRe
import excelxml
from excelxml import OXLLoader, regex_range, unescape, excel_col_to_int, wscell_address, offset_rng, wscell_pattern

In [3]:
fpath = pathlib.Path(r'C:\Users\agmontesb\Documents\DIAN\Renta2025\F2517_AG2025')
fname = 'Reporte_Conciliación_Fiscal_F2517V8_AG2025_v1.0.0-2026.xlsm'
full_path = fpath / fname

In [4]:
loader = OXLLoader(full_path)

In [5]:
fout = r'C:\Users\agmontesb\Documents\GitHub\excel\tests\files\h3_eri_renta_liquida.xml'
# with open(fout, 'w') as f:
#     f.write(h3_xml)

In [6]:
from excel_workbook import ExcelWorkbook, ExcelWorksheet, ExcelTable, pythonize_fml

In [7]:
wb = excelxml.WorkBookXml(full_path)
ws = wb.active
ws.title
# wb.load_wb_data(full_path)

DEBUG:excelxml:Error loading named ranges: Invalid cell reference: #NAME?

'H3 (ERI - Renta Liquida)'

In [8]:
nrow = 378
row = ws[f'{nrow}:{nrow}']
row

{'A378': Cell(address='A378', formula_='A377+1', value=378, style='350', span=[np.int64(318079), np.int64(318136)]),
 'D378': Cell(address='D378', formula_=None, value='Total ingreso cedular (valor fiscal)', style='1100', span=[np.int64(318180), np.int64(318221)]),
 'H378': Cell(address='H378', formula_='L10-L12', value=0, style='379', span=[np.int64(318287), np.int64(318333)]),
 'I378': Cell(address='I378', formula_='+L12', value=0, style='379', span=[np.int64(318333), np.int64(318376)]),
 'J378': Cell(address='J378', formula_='L25', value=7578508, style='379', span=[np.int64(318376), np.int64(318424)]),
 'K378': Cell(address='K378', formula_='IF(N37>0,L37-N37,L37)', value=0, style='379', span=[np.int64(318424), np.int64(318487)]),
 'L378': Cell(address='L378', formula_='H378+I378+J378+K378', value=7578508, style='379', span=[np.int64(318487), np.int64(318586)]),
 'M378': Cell(address='M378', formula_='L20', value=25996270, style='379', span=[np.int64(318586), np.int64(318635)]),
 'N378': Cell(address='N378', formula_='N37', value=0, style='393', span=[np.int64(318635), np.int64(318677)])}

In [9]:
fnc = lambda x: '{0: >4s}{1: >4s}'.format(*excelxml.wscell_address(x))

In [10]:
gnc = lambda x: any(map(x.startswith, tuple('GHIJKLMN')))
gnc('N23')

True

In [11]:
ws_range = 'H9:N671'
cells = ws[ws_range]

In [12]:
values = {key: cell.value for key, cell in cells.items() if cell.value is not None}
fmls = {key: cell.formula for key, cell in cells.items() if cell.formula}

In [13]:
row = {key: value for key, value in cells.items() if gnc(key) and key.endswith('378')}
{key: row[key] for key in sorted(row.keys(), key=lambda x: fnc(x))}

{'H378': Cell(address='H378', formula_='L10-L12', value=0, style='379', span=[np.int64(318287), np.int64(318333)]),
 'I378': Cell(address='I378', formula_='+L12', value=0, style='379', span=[np.int64(318333), np.int64(318376)]),
 'J378': Cell(address='J378', formula_='L25', value=7578508, style='379', span=[np.int64(318376), np.int64(318424)]),
 'K378': Cell(address='K378', formula_='IF(N37>0,L37-N37,L37)', value=0, style='379', span=[np.int64(318424), np.int64(318487)]),
 'L378': Cell(address='L378', formula_='H378+I378+J378+K378', value=7578508, style='379', span=[np.int64(318487), np.int64(318586)]),
 'M378': Cell(address='M378', formula_='L20', value=25996270, style='379', span=[np.int64(318586), np.int64(318635)]),
 'N378': Cell(address='N378', formula_='N37', value=0, style='393', span=[np.int64(318635), np.int64(318677)])}

In [14]:
ws_name = ws.title
ws_name, full_path, ws_range

('H3 (ERI - Renta Liquida)',
 WindowsPath('C:/Users/agmontesb/Documents/DIAN/Renta2025/F2517_AG2025/Reporte_Conciliación_Fiscal_F2517V8_AG2025_v1.0.0-2026.xlsm'),
 'H9:N671')

In [15]:
excel_wb = ExcelWorkbook(full_path)
excel_wb.create_worksheet('H4 (Impuesto Diferido)')
wsheet = excel_wb.create_worksheet(ws_name)

In [16]:
# cells = ws_data['cells']
keys = sorted(cells, key=lambda x:fnc(x))
fmls = {key: f"={cells[key][1].lstrip('=+')}" for key in keys if gnc(key) and cells[key][1] is not None}
all_values = {key: cells[key][2] for key in keys if gnc(key) and not isinstance(cells[key][2], str)}

In [17]:
values = {key: all_values[key] for key in (all_values.keys() - fmls.keys())}

In [18]:
fmls['K595']

"=IF(AND(L599>='H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448,'H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448>=L598),L598,IF(AND(L599>=M599,'H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448<L598),'H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448,IF(AND(L597<'H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448,'H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448>=L598),L598,'H4 (Impuesto Diferido)'!D81+'H4 (Impuesto Diferido)'!D82-J448-L448)))"

In [19]:
pythonize_fml(fmls['K595'], table_name='tbl')

'=xlf.if_(xlf.and_(tbl[\'L599\'].values>=tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values,tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values>=tbl[\'L598\'].values),tbl[\'L598\'].values,xlf.if_(xlf.and_(tbl[\'L599\'].values>=tbl[\'M599\'].values,tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values<tbl[\'L598\'].values),tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values,xlf.if_(xlf.and_(tbl[\'L597\'].values<tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values,tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values>=tbl[\'L598\'].values),tbl[\'L598\'].values,tbl["\'H4 (Impuesto Diferido)\'!D81"].values+tbl["\'H4 (Impuesto Diferido)\'!D82"].values-tbl[\'J448\'].values-tbl[\'L448\'].values)))'

In [20]:
sht_tbl = ExcelTable(wsheet, 'Renta_liquida', ws_range, fmls=fmls, values=values)

In [21]:
sht_tbl.parent.parameters(M6=49799)

In [22]:
mtable = sht_tbl.minimun_table()

In [23]:
from xlobjects import EmptyCell

In [24]:
bool(EmptyCell())

False

In [32]:
mask = mtable.any(axis=1)
mtable[mask]

col,H,I,J,K,L,M,N
row,,,,,,,
20,25996270,0,0,0,25996270,,0
21,25996270,0,0,0,25996270,,0
25,7578508,0,0,0,7578508,,0
26,7578508,0,0,0,7578508,,0
141,0,0,0,3735400,3735400,,0
142,33574778,0,0,-3735400,29839378,,0
207,68109,0,34055,0,34054,,0
212,68109,0,34055,0,34054,,0
213,3735400,0,3735400,0,0,,0
219,3735400,0,3735400,0,0,,0
239,3735400,0,3735400,0,0,,0
317,607484,0,607484,0,0,,0
326,607484,0,607484,0,0,,0
354,31184701,0,31184701,0,0,,0
357,31184701,0,31184701,0,0,,0
361,35595694,0,35561640,0,34054,,0
362,-2020916,0,-35561640,-3735400,29805324,,0
378,0,0,7578508,0,7578508,25996270,0
382,0,0,3735400,0,3735400,0,0
383,0,0,683400,0,-683400,0,0
386,0,0,3052000,0,-3052000,0,0
395,0,0,3843108,0,3843108,25996270,0
398,0,0,3843108,0,3843108,25996270,0
410,0,0,34054,0,34054,0,0
417,0,0,34054,0,-34054,0,0
443,0,0,34054,0,34054,0,0
444,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,0,#UNKNOWN!
445,,,,,#UNKNOWN!,#UNKNOWN!,
446,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,25996270,#UNKNOWN!
457,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,25996270,#UNKNOWN!
461,,,,,#UNKNOWN!,,
462,,,,,3735400,,
464,,,,,#UNKNOWN!,,
474,,,,,35561640,,
476,,,,,34055,,
498,,,,,35527585,,
504,,,,,#UNKNOWN!,,
573,,,,,#UNKNOWN!,,
574,,,,,#UNKNOWN!,,
576,,,,,#UNKNOWN!,,
577,,,,,204481000,,
585,,,,,#UNKNOWN!,,
586,,,,,#UNKNOWN!,,
588,,,,,#UNKNOWN!,,
608,,,,,17127000,,
613,,,,,291453,,
617,,,,,291453,,
636,0,2020916,,,,,

In [35]:
tbl = sht_tbl

In [37]:
tbl.get_formula('383')

col  H  I       J  K                     L  M  N
row
383  0  0  683400  0  =H383+I383+J383+K383  0  0

In [44]:
tbl.set_records({'J383': 683400}, 'value')

In [47]:
tbl.recalculate(True)

In [50]:
dmy = tbl.minimun_table()
mask = dmy.any(axis=1)
dmy[mask]

col,H,I,J,K,L,M,N
row,,,,,,,
20,25996270,0,0,0,25996270,,0
21,25996270,0,0,0,25996270,,0
25,7578508,0,0,0,7578508,,0
26,7578508,0,0,0,7578508,,0
141,0,0,0,3735400,3735400,,0
142,33574778,0,0,-3735400,29839378,,0
207,68109,0,34055,0,34054,,0
212,68109,0,34055,0,34054,,0
213,3735400,0,3735400,0,0,,0
219,3735400,0,3735400,0,0,,0
239,3735400,0,3735400,0,0,,0
317,607484,0,607484,0,0,,0
326,607484,0,607484,0,0,,0
354,31184701,0,31184701,0,0,,0
357,31184701,0,31184701,0,0,,0
361,35595694,0,35561640,0,34054,,0
362,-2020916,0,-35561640,-3735400,29805324,,0
378,0,0,7578508,0,7578508,25996270,0
382,0,0,3735400,0,3735400,0,0
383,0,0,683400,0,683400,0,0
386,0,0,3052000,0,-3052000,0,0
395,0,0,3843108,0,3843108,25996270,0
398,0,0,3843108,0,3843108,25996270,0
410,0,0,34054,0,34054,0,0
417,0,0,34054,0,-34054,0,0
443,0,0,34054,0,34054,0,0
444,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,0,#UNKNOWN!
445,,,,,#UNKNOWN!,#UNKNOWN!,
446,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,25996270,#UNKNOWN!
457,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,#UNKNOWN!,25996270,#UNKNOWN!
461,,,,,#UNKNOWN!,,
462,,,,,3735400,,
464,,,,,#UNKNOWN!,,
474,,,,,35561640,,
476,,,,,34055,,
498,,,,,35527585,,
504,,,,,#UNKNOWN!,,
573,,,,,#UNKNOWN!,,
574,,,,,#UNKNOWN!,,
576,,,,,#UNKNOWN!,,
577,,,,,204481000,,
585,,,,,#UNKNOWN!,,
586,,,,,#UNKNOWN!,,
588,,,,,#UNKNOWN!,,
608,,,,,17127000,,
613,,,,,291453,,
617,,,,,291453,,
636,0,2020916,,,,,

In [ ]:
pythonize_fml(fmls['L386'], table_name='tbl')

In [ ]:
mtable.loc['386']

In [ ]:
sht_tbl.set_records(values, field='value')

In [ ]:
sht_tbl.set_records(fmls, field='fml')

In [ ]:

# Acá se hace una corrección ya que la celda 'G142' es un valor pero se encuentra expresada como formula 
# =151647+1
fmls.pop('G142')
all_values['G142'] = 151_647 + 1

In [ ]:
ws_name = wb.sheetnames[12]
wsheet = excel_wb.create_worksheet(ws_name)
sht_tbl = ExcelTable(wsheet, 'ESF_Patrimonio', 'G11:K227', fmls=fmls, values=values)

In [ ]:
nrow = 141
sht_tbl[f'G{nrow}:K{nrow}']

In [ ]:
mask = sht_tbl.data.value != 0
keys = sht_tbl.data[mask].index.tolist()

In [ ]:
sht_tbl[keys]

In [ ]:

df_value = sht_tbl.data.value
mask = sht_tbl.data.value != 0
df_values = df_value[mask].to_dict()

In [ ]:
vals_na = {key: value for key, value in all_values.items() if value != 0}

In [ ]:
df_values == vals_na

In [ ]:
cell = 'G12'
sht_tbl.data.loc[cell]

In [ ]:
to_init =

In [ ]:
to_init = sorted(values.keys(), key=lambda x: '{0: >4s}{1}'.format(*excelxml.wscell_address(x)))
changed = sht_tbl.get_cells_to_calc(to_init, isCoded=False)

In [ ]:
changed_cal = sorted({int(wscell_address(x)[0]) for x in changed})

In [ ]:
changed_tbl = sht_tbl[keys].index.astype("int64").tolist()

In [ ]:
changed_cal == changed_tbl

In [ ]:
regex_str = r'(?#<row r=radr <c r=cadr v.*=val>>)'
cpat = MarkupRe.compile(regex_str)

In [ ]:
srchObj = cpat.srchRegexObj
srchObj.var_list

In [ ]:
srchStr = r'<sheetData><row r="2" spans="1:9" ht="39.75" customHeight="1" x14ac:dyDescent="0.25"><c r="F2" t="s"><v>15</v></c><c r="G2"><v>0</v></c></row><row r="3" spans="1:9" ht="39.75" customHeight="1" x14ac:dyDescent="0.25"><c r="A3"><v>1</v></c><c r="B3"><v>2</v></c><c r="E3" t="s"><v>11</v></c></row>'

In [ ]:
m = cpat.search(srchStr)

In [ ]:
m.groupdict()

In [ ]:
def iter_rows(min_row=None, min_col=None, max_row=None, max_col=None, values_only=False):
    pass

In [ ]:
srchRgx = r'<c r="(?P<adr>[A-Z]+\d+)" s="(?P<style>\w+)"/>'

In [ ]:
cpat = excelxml.re.compile(srchRgx)

In [ ]:
m = cpat.search(h3_xml)

In [ ]:
mit = cpat.finditer(h3_xml)
styles = [(*m.span(), m.group('adr'), m.group('style')) for m in mit]

In [ ]:
styles[-1]

In [ ]:
(*m.span(), m.group('adr'), m.group('style'))

In [ ]:
v_srchRgx = r'<c r="(?P<adr>[A-Z]+\d+)"(?: s="(?P<style>\w+)")*( t="(?P<type>\w+)")*>(?:<f>(?P<fml>.+?)</f>)*<v>(?P<val>.+?)</v></c>'

In [ ]:
cpat = excelxml.re.compile(v_srchRgx)

In [ ]:
m = cpat.search(h3_xml)
m

In [ ]:
values = [(m.span(), *m.groupdict().values()) for m in cpat.finditer(h3_xml)]

In [ ]:
len(values)

In [ ]:
values[-1]

In [ ]:
import re
from typing import Any, Callable, Generator, Iterable, Iterator, Literal, Optional, Union

In [ ]:
link_pattern = re.compile(r"((?:'(?:.+?)'!)+(?:\$?[A-Z])+(?:\$?[0-9])+)")
cell_pattern = re.compile(r"(?:'(?P<sht>.+?)'!)*(?P<col>\$?[A-Z]+)(?P<row>\$?[0-9]+)")
cell_address:Callable[[str], tuple[str, ...]] = lambda cell: tuple(x for x in cell_pattern.search(cell).groups()[::-1] if x)
rgn_pattern_grp = re.compile("(?:'(?P<sht>.+?)'!)*(?P<col>\\$?[A-Z]+)(?P<row>\\$?[0-9]+)(?::\\$?[A-Z]\\$?[0-9]+)?")
rgn_pattern = re.compile(r"(?:'.+?'!)*\$?[A-Z]\$?[0-9]+(?::\$?[A-Z]\$?[0-9]+)?")
tbl_pattern = re.compile(r"(?:'(?P<sht>.+?)'!)*(?P<cell>.+)")
tbl_address = lambda tbl: tbl_pattern.match(tbl).groups()

In [ ]:
def cells_in_range(ref_range: str, excel_slice: tuple[str, ...] | str) -> list[str]:
    parent_title, ref_range = tbl_address(ref_range)
    (rmin, cmin),  (rmax, cmax) = map( cell_address, ref_range.split(':'))
    rmin, rmax = int(rmin), int(rmax)

    if isinstance(excel_slice, str):
        excel_slice = (excel_slice, )
    cell_rgn = set()
    for slice in excel_slice:
        sheet, slice = tbl_address(slice)
        prefix = '' if sheet in (None, parent_title) else f'\'{sheet}\'!'
        slice = slice.upper().replace('$', '')
        linf, lsup = f'{slice}:{slice}'.split(':', 2)[:2]
        if (linf + lsup).isnumeric():
            if not prefix and (rmin <= int(linf) <= rmax) and (rmin <= int(lsup) <= rmax):
                linf = f'{cmin}{linf}'
                lsup = f'{cmax}{lsup}'
            else: 
                continue
        if (linf + lsup).isalpha():
            if not prefix and (cmin <= linf <= cmax) and (cmin <= lsup <= cmax):
                linf = f'{linf}{rmin}'
                lsup = f'{lsup}{rmax}'
            else:    
                continue
        linf_cell = cell_address(linf)
        lsup_cell = cell_address(lsup)
        fnc = lambda x: sum((ord(c) - ord('A') + 1) * (26 ** i) for i, c in enumerate(reversed(x)))
        linf_cell, lsup_cell = map(lambda x: (int(x[0]), int(fnc(x[1]))), (linf_cell, lsup_cell))
        cell_rgn.update(
            [
                f'{prefix}{col}{row}' for row, col in itertools.product(
                [x for x in range(linf_cell[0], lsup_cell[0] + 1)],
                [alpha_code(x) for x in range(linf_cell[1], lsup_cell[1] + 1)])
            ]
        )
    cell_rgn = sorted(cell_rgn, key=lambda x: '{0: >4s}{1: >4s}'.format(*cell_address(x)))

In [ ]:
ref_range = "'Shee1'!A1:ZA200"
excel_slice= ('C:J', '10:20', 'g25', 'A190:D300')

In [ ]:
parent_title, ref_range = tbl_address(ref_range)
(rmin, cmin),  (rmax, cmax) = map( cell_address, ref_range.split(':'))
rmin, rmax = int(rmin), int(rmax)
cell_rgn = set()

In [ ]:
slice = excel_slice[0]
sheet, slice = tbl_address(slice)
prefix = '' if sheet in (None, parent_title) else f'\'{sheet}\'!'
slice = slice.upper().replace('$', '')
linf, lsup = f'{slice}:{slice}'.split(':', 2)[:2]
(linf + lsup).isalpha()
not prefix and (cmin <= linf <= cmax) and (cmin <= lsup <= cmax)
linf = f'{linf}{rmin}'
lsup = f'{lsup}{rmax}'
linf, lsup

In [ ]:
linf_cell = cell_address(linf)
lsup_cell = cell_address(lsup)
linf_cell, lsup_cell

In [ ]:
fnc = lambda x: sum((ord(c) - ord('A') + 1) * (26 ** i) for i, c in enumerate(reversed(x)))

In [ ]:
linf_cell, lsup_cell = map(lambda x: (int(x[0]), int(fnc(x[1]))), (linf_cell, lsup_cell))
linf_cell, lsup_cell

In [ ]:
fnc('AZ')